FROM node:20-alpine AS build

WORKDIR /web

COPY package.json /web/package.json
RUN npm install

COPY . /web
RUN npm run build

FROM nginx:1.27-alpine

COPY --from=build /web/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
